version = 3

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}}'
    foreground = 'cyan'
    type = 'os'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = 'cyan'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = ':: {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }} '
    foreground = '#F1502F'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '| root '
    foreground = 'red'
    type = 'root'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '|  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#06A4CE'
    type = 'dart'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = "|  {{ .Full }} "
    foreground = '#7FD5EA'
    type = 'go'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = "| 󱘗 {{ .Full }} "
    foreground = '#F5710A'
    type = 'rust'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = "|  {{ .Full }} "
    foreground = '#F72B34'
    type = 'java'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = "|  {{ .Full }} "
    foreground = '#1C6AC2'
    type = 'lua'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '|  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    foreground = '#6CA35E'
    type = 'node'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '|  {{ .Venv }} '
    foreground = '#4584b6'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'context'
      fetch_virtual_env = true

  [[blocks.segments]]
    template = '| {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}  '
    type = 'battery'
    style = 'powerline'
    foreground_templates = ['{{if eq "Charging" .State.String}}#4caf50{{end}}', '{{if eq "Discharging" .State.String}}#40c4ff{{end}}', '{{if eq "Full" .State.String}}#ff0000{{end}}']
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'
      charged_icon = ' '
      charging_icon = ' '

  [[blocks.segments]]
    template = '| {{ .CurrentDate | date .Format }} '
    foreground = 'lightGreen'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' '
    foreground = 'lightGreen'
    type = 'status'
    style = 'powerline'
    foreground_templates = ['{{ if gt .Code 0 }}red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
